version: '3'

services:

  musicutilweb:
    container_name: musicutilweb
    restart: always
    build: ./musicutilweb
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b :8000 manage:app


  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - musicutilweb
